name: Python CI

on:
  push:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Python
        run: python app.py

      - name: Build Docker image
        run: docker build -t github-actions-learning .
